apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 8080
        command: 
        - bash
        - "-c"
        - |
          cat <<EOF > /usr/share/nginx/html/index.html
          "hello world"
          EOF
          nginx -g "daemon off;"

